-- ClavelParts · Seed de tipos_pieza
-- Ejecutar en Supabase SQL Editor

INSERT INTO public.tipos_pieza (subgrupo_id, nombre, orden)
SELECT sg.id, x.nombre, x.orden
FROM public.subgrupos sg
JOIN public.grupos g ON g.id = sg.grupo_id
JOIN (VALUES
  -- ── Motor ──────────────────────────────────────────────────
  ('Motor',          'Junta de Tapa',          'Junta tapa de válvulas',           10),
  ('Motor',          'Junta de Tapa',          'Junta tapa de cilindros',          20),
  ('Motor',          'Junta de Culata',        'Junta de culata',                  10),
  ('Motor',          'Junta de Culata',        'Juego de juntas motor completo',   20),
  ('Motor',          'Pistones y Aros',        'Pistón completo',                  10),
  ('Motor',          'Pistones y Aros',        'Juego de aros',                    20),
  ('Motor',          'Pistones y Aros',        'Bulón de pistón',                  30),
  ('Motor',          'Cigüeñal',               'Cigüeñal nuevo',                   10),
  ('Motor',          'Cigüeñal',               'Cigüeñal rectificado',             20),
  ('Motor',          'Cigüeñal',               'Kit de cigüeñal',                  30),
  ('Motor',          'Árbol de levas',         'Árbol de levas',                   10),
  ('Motor',          'Válvulas',               'Válvula de admisión',              10),
  ('Motor',          'Válvulas',               'Válvula de escape',                20),
  ('Motor',          'Válvulas',               'Juego de válvulas',                30),
  ('Motor',          'Bielas',                 'Biela',                            10),
  ('Motor',          'Bielas',                 'Juego de bielas',                  20),
  ('Motor',          'Metales de biela',       'Metales de biela estándar',        10),
  ('Motor',          'Metales de biela',       'Metales de biela sobremedida',     20),
  ('Motor',          'Bancadas',               'Metales de bancada estándar',      10),
  ('Motor',          'Bancadas',               'Metales de bancada sobremedida',   20),
  ('Motor',          'Balancines',             'Balancín',                         10),
  ('Motor',          'Poleas de motor',        'Polea de cigüeñal',                10),
  ('Motor',          'Poleas de motor',        'Polea tensora',                    20),
  ('Motor',          'Retenes de válvula',     'Retén de válvula',                 10),
  ('Motor',          'Tapones de bloque',      'Tapón de bloque',                  10),
  ('Motor',          'Bloque motor',           'Bloque de motor',                  10),
  ('Motor',          'Tapa de cilindros',      'Tapa de cilindros',                10),
  ('Motor',          'Tornillos de tapa',      'Tornillos de culata',              10),
  ('Motor',          'Botadores',              'Botador de válvula',               10),
  ('Motor',          'Guías de válvula',       'Guía de válvula',                  10),
  ('Motor',          'Asientos de válvula',    'Asiento de válvula',               10),
  -- ── Distribución ───────────────────────────────────────────
  ('Distribución',   'Correa de distribución', 'Correa de distribución',           10),
  ('Distribución',   'Kit de distribución',    'Kit completo con bomba',           10),
  ('Distribución',   'Kit de distribución',    'Kit sin bomba',                    20),
  ('Distribución',   'Tensor de distribución', 'Tensor de correa',                 10),
  ('Distribución',   'Cadena de distribución', 'Cadena de distribución',           10),
  ('Distribución',   'Guía de cadena',         'Guía de cadena',                   10),
  ('Distribución',   'Engranajes de distribución','Piñón de cigüeñal',            10),
  ('Distribución',   'Engranajes de distribución','Piñón de árbol de levas',      20),
  -- ── Lubricación ────────────────────────────────────────────
  ('Lubricación',    'Bomba de aceite',        'Bomba de aceite',                  10),
  ('Lubricación',    'Filtro de aceite',       'Filtro de aceite',                 10),
  ('Lubricación',    'Carter',                 'Cárter de aceite',                 10),
  ('Lubricación',    'Carter',                 'Junta de cárter',                  20),
  ('Lubricación',    'Tapón de carter',        'Tapón magnético',                  10),
  ('Lubricación',    'Tapón de carter',        'Tapón con arandela',               20),
  ('Lubricación',    'Enfriador de aceite',    'Enfriador de aceite',              10),
  -- ── Encendido ──────────────────────────────────────────────
  ('Encendido',      'Bujías',                 'Bujía estándar',                   10),
  ('Encendido',      'Bujías',                 'Bujía de iridio',                  20),
  ('Encendido',      'Bujías',                 'Bujía de platino',                 30),
  ('Encendido',      'Bobina de encendido',    'Bobina individual',                10),
  ('Encendido',      'Bobina de encendido',    'Bobina de distribuidor',           20),
  ('Encendido',      'Cables de bujía',        'Juego de cables de bujía',        10),
  ('Encendido',      'Distribuidor',           'Distribuidor completo',            10),
  ('Encendido',      'Distribuidor',           'Tapa de distribuidor',             20),
  ('Encendido',      'Distribuidor',           'Rotor de distribuidor',            30),
  ('Encendido',      'Módulo de encendido',    'Módulo de encendido',              10),
  -- ── Suspensión ─────────────────────────────────────────────
  ('Suspensión',     'Amortiguadores',         'Amortiguador delantero',           10),
  ('Suspensión',     'Amortiguadores',         'Amortiguador trasero',             20),
  ('Suspensión',     'Amortiguadores',         'Cazoleta de amortiguador',         30),
  ('Suspensión',     'Amortiguadores',         'Kit amortiguador + resorte',       40),
  ('Suspensión',     'Bujes',                  'Buje de parrilla',                 10),
  ('Suspensión',     'Bujes',                  'Buje de barra estabilizadora',     20),
  ('Suspensión',     'Bujes',                  'Buje de brazo de control',         30),
  ('Suspensión',     'Rotulas',                'Rótula de dirección',              10),
  ('Suspensión',     'Rotulas',                'Rótula de mangueta',               20),
  ('Suspensión',     'Barra Estabilizadora',   'Barra estabilizadora delantera',   10),
  ('Suspensión',     'Barra Estabilizadora',   'Barra estabilizadora trasera',     20),
  ('Suspensión',     'Barra Estabilizadora',   'Tensor de barra estabilizadora',   30),
  -- ── Dirección ──────────────────────────────────────────────
  ('Dirección',      'Caja de dirección',      'Caja de dirección mecánica',       10),
  ('Dirección',      'Caja de dirección',      'Caja de dirección hidráulica',     20),
  ('Dirección',      'Bomba de dirección hidráulica','Bomba de dirección',        10),
  ('Dirección',      'Cremallera de dirección','Cremallera de dirección',          10),
  ('Dirección',      'Terminales de dirección','Terminal de dirección',            10),
  ('Dirección',      'Terminales de dirección','Par de terminales',                20),
  ('Dirección',      'Columna de dirección',   'Columna de dirección',             10),
  ('Dirección',      'Mangueras de dirección', 'Manguera de alta presión',         10),
  ('Dirección',      'Mangueras de dirección', 'Manguera de retorno',              20),
  -- ── Frenos ─────────────────────────────────────────────────
  ('Frenos',         'Pastillas',              'Pastillas delanteras',             10),
  ('Frenos',         'Pastillas',              'Pastillas traseras',               20),
  ('Frenos',         'Pastillas',              'Pastillas cerámicas delanteras',   30),
  ('Frenos',         'Pastillas',              'Pastillas cerámicas traseras',     40),
  ('Frenos',         'Discos',                 'Disco delantero liso',             10),
  ('Frenos',         'Discos',                 'Disco trasero liso',               20),
  ('Frenos',         'Discos',                 'Disco ventilado delantero',        30),
  ('Frenos',         'Discos',                 'Disco perforado',                  40),
  ('Frenos',         'Bombín',                 'Bombín de freno',                  10),
  ('Frenos',         'Bomba de Freno',         'Bomba de freno',                   10),
  ('Frenos',         'Flexible de Freno',      'Flexible de freno delantero',      10),
  ('Frenos',         'Flexible de Freno',      'Flexible de freno trasero',        20),
  -- ── Transmisión ────────────────────────────────────────────
  ('Transmisión',    'Caja de cambios',        'Caja de cambios completa',         10),
  ('Transmisión',    'Diferencial',            'Diferencial completo',             10),
  ('Transmisión',    'Palieres',               'Palier completo',                  10),
  ('Transmisión',    'Palieres',               'Fuelle de palier',                 20),
  ('Transmisión',    'Crucetas',               'Cruceta de cardán',                10),
  ('Transmisión',    'Rodamientos de rueda',   'Rodamiento de rueda delantero',    10),
  ('Transmisión',    'Rodamientos de rueda',   'Rodamiento de rueda trasero',      20),
  ('Transmisión',    'Juntas homocinéticas',   'Homocinética delantera exterior',  10),
  ('Transmisión',    'Juntas homocinéticas',   'Homocinética delantera interior',  20),
  ('Transmisión',    'Juntas homocinéticas',   'Kit homocinética completo',        30),
  -- ── Embrague ───────────────────────────────────────────────
  ('Embrague',       'Kit de embrague',        'Kit completo (disco+plato+rulemán)',10),
  ('Embrague',       'Disco de embrague',      'Disco de embrague',                10),
  ('Embrague',       'Plato de presión',       'Plato de presión',                 10),
  ('Embrague',       'Rulemán de embrague',    'Rulemán de embrague',              10),
  ('Embrague',       'Cable de embrague',      'Cable de embrague',                10),
  ('Embrague',       'Volante motor',          'Volante motor bimasa',             10),
  ('Embrague',       'Volante motor',          'Volante motor sólido',             20),
  -- ── Electricidad Interior ───────────────────────────────────
  ('Electricidad Interior','Alternador',       'Alternador nuevo',                 10),
  ('Electricidad Interior','Alternador',       'Alternador remanufacturado',       20),
  ('Electricidad Interior','Motor de arranque','Motor de arranque',                10),
  ('Electricidad Interior','Batería',          'Batería estándar',                 10),
  ('Electricidad Interior','Batería',          'Batería AGM',                      20),
  ('Electricidad Interior','Sensores',         'Sensor ABS delantero',             10),
  ('Electricidad Interior','Sensores',         'Sensor ABS trasero',               20),
  ('Electricidad Interior','Sensores',         'Sensor de temperatura exterior',   30),
  ('Electricidad Interior','Relay y fusibles', 'Relay',                            10),
  ('Electricidad Interior','Relay y fusibles', 'Caja de fusibles',                 20),
  ('Electricidad Interior','Cableado',         'Mazo de cables',                   10),
  -- ── A/C y Calefacción ──────────────────────────────────────
  ('A/C y Calefacción','Compresor de A/C',     'Compresor de A/C nuevo',           10),
  ('A/C y Calefacción','Compresor de A/C',     'Compresor de A/C remanufacturado', 20),
  ('A/C y Calefacción','Condensador',          'Condensador de A/C',               10),
  ('A/C y Calefacción','Evaporador',           'Evaporador de A/C',                10),
  ('A/C y Calefacción','Filtro de cabina',     'Filtro de habitáculo',             10),
  ('A/C y Calefacción','Válvula de expansión', 'Válvula de expansión',             10),
  ('A/C y Calefacción','Electroventilador de A/C','Electroventilador de A/C',     10),
  ('A/C y Calefacción','Radiador de calefacción','Radiador de calefacción',        10),
  -- ── Inyección y Admisión ───────────────────────────────────
  ('Inyección y Admisión','Inyectores',        'Inyector',                         10),
  ('Inyección y Admisión','Inyectores',        'Juego de inyectores',              20),
  ('Inyección y Admisión','Cuerpo de aceleración','Cuerpo de aceleración',         10),
  ('Inyección y Admisión','Filtro de aire',    'Filtro de aire',                   10),
  ('Inyección y Admisión','Múltiple de admisión','Múltiple de admisión',           10),
  ('Inyección y Admisión','Regulador de presión','Regulador de presión',           10),
  ('Inyección y Admisión','Sensor MAP/MAF',    'Sensor MAP',                       10),
  ('Inyección y Admisión','Sensor MAP/MAF',    'Sensor MAF (caudalímetro)',         20),
  ('Inyección y Admisión','Bomba de combustible','Bomba de combustible',           10),
  -- ── Refrigeración ──────────────────────────────────────────
  ('Refrigeración',  'Bomba de Agua',          'Bomba de agua',                    10),
  ('Refrigeración',  'Termostato',             'Termostato',                       10),
  ('Refrigeración',  'Termostato',             'Termostato con carcasa',           20),
  ('Refrigeración',  'Radiador',               'Radiador de agua',                 10),
  ('Refrigeración',  'Tapa Radiador',          'Tapa de radiador',                 10),
  ('Refrigeración',  'Electro Ventilador',     'Electroventilador',                10),
  ('Refrigeración',  'Mangueras',              'Manguera superior',                10),
  ('Refrigeración',  'Mangueras',              'Manguera inferior',                20),
  ('Refrigeración',  'Mangueras',              'Juego de mangueras',               30),
  -- ── Escape ─────────────────────────────────────────────────
  ('Escape',         'Catalizador',            'Catalizador original',             10),
  ('Escape',         'Catalizador',            'Catalizador universal',            20),
  ('Escape',         'Múltiple de escape',     'Múltiple de escape',               10),
  ('Escape',         'Caño de escape',         'Caño intermedio',                  10),
  ('Escape',         'Caño de escape',         'Caño final con silenciador',       20),
  ('Escape',         'Silenciador',            'Silenciador trasero',              10),
  ('Escape',         'Juntas de escape',       'Junta de múltiple',                10),
  ('Escape',         'Juntas de escape',       'Juego de juntas escape',           20),
  ('Escape',         'Sensor de oxígeno',      'Sensor lambda anterior',           10),
  ('Escape',         'Sensor de oxígeno',      'Sensor lambda posterior',          20),
  -- ── Ruedas y Neumáticos ────────────────────────────────────
  ('Ruedas y Neumáticos','Neumáticos',         'Neumático de verano',              10),
  ('Ruedas y Neumáticos','Neumáticos',         'Neumático de invierno',            20),
  ('Ruedas y Neumáticos','Neumáticos',         'Neumático all-season',             30),
  ('Ruedas y Neumáticos','Llantas',            'Llanta de chapa',                  10),
  ('Ruedas y Neumáticos','Llantas',            'Llanta de aleación',               20),
  ('Ruedas y Neumáticos','Válvulas de rueda',  'Válvula de rueda',                 10),
  ('Ruedas y Neumáticos','Tapas de rueda',     'Tapa de rueda',                    10),
  ('Ruedas y Neumáticos','Bulones de rueda',   'Bulón de rueda',                   10),
  ('Ruedas y Neumáticos','Bulones de rueda',   'Tuerca de rueda',                  20),
  -- ── Carrocería ─────────────────────────────────────────────
  ('Carrocería',     'Paragolpes',             'Paragolpe delantero imprimado',    10),
  ('Carrocería',     'Paragolpes',             'Paragolpe trasero imprimado',      20),
  ('Carrocería',     'Guardabarros',           'Guardabarros delantero',           10),
  ('Carrocería',     'Guardabarros',           'Guardabarros trasero',             20),
  ('Carrocería',     'Capó',                   'Capó',                             10),
  ('Carrocería',     'Puertas',                'Puerta delantera',                 10),
  ('Carrocería',     'Puertas',                'Puerta trasera',                   20),
  ('Carrocería',     'Espejos retrovisores',   'Espejo retrovisor derecho',        10),
  ('Carrocería',     'Espejos retrovisores',   'Espejo retrovisor izquierdo',      20),
  ('Carrocería',     'Espejos retrovisores',   'Tapa de espejo',                   30),
  ('Carrocería',     'Ópticas',                'Óptica delantera derecha',         10),
  ('Carrocería',     'Ópticas',                'Óptica delantera izquierda',       20),
  ('Carrocería',     'Faros traseros',         'Faro trasero derecho',             10),
  ('Carrocería',     'Faros traseros',         'Faro trasero izquierdo',           20),
  ('Carrocería',     'Vidrios',                'Parabrisas',                       10),
  ('Carrocería',     'Vidrios',                'Luneta trasera',                   20),
  ('Carrocería',     'Molduras',               'Moldura de puerta',                10),
  ('Carrocería',     'Molduras',               'Moldura de capó',                  20),
  -- ── Accesorios ─────────────────────────────────────────────
  ('Accesorios',     'Fundas y cubre asientos','Fundas de asiento',               10),
  ('Accesorios',     'Alfombras',              'Juego de alfombras',               10),
  ('Accesorios',     'Alfombras',              'Tapetes de goma',                  20),
  ('Accesorios',     'Portaequipajes',         'Portaequipaje de techo',           10),
  ('Accesorios',     'Estéreo y audio',        'Radio / pantalla',                 10),
  ('Accesorios',     'Luces LED',              'Kit LED interior',                 10),
  ('Accesorios',     'Luces LED',              'Kit LED faros',                    20),
  ('Accesorios',     'Alarma',                 'Alarma con corte',                 10)
) AS x(grupo_nombre, subgrupo_nombre, nombre, orden)
  ON x.grupo_nombre = g.nombre AND x.subgrupo_nombre = sg.nombre
ON CONFLICT (subgrupo_id, nombre) DO NOTHING;
